duckdb_profile:
  target: dev
  outputs:
    dev:
      path: receipts.duckdb
      type: duckdb
      extensions:
        - httpfs
      threads: 1
    prod:
      path: /opt/airflow/dbt/airbnb/receipts.duckdb
      type: duckdb
      extensions:
        - httpfs
      threads: 1
